# Generated by Django 5.1.3 on 2024-12-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
